name: Build an image with the signature

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        packages: write
        id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: install cosign
        uses: sigstore/cosign-installer@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          # Suppose that your repository is located at https://github.com/<X>/<Y>, this value should be equal to X
          username: hikaru0112
          password: ${{ github.token }}

      # TODO: add cosign-installer etc.
      #use docker
      - name: Prepare Dockerfile
        run: |
          echo "FROM alpine:3.10" > Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          # Suppose that your repository is located at https://github.com/<X>/<Y>, this value should be equal to ghcr.io/<X>/<random value>:latest
          tags: |
            ghcr.io/hikaru0112/test-image:latest
          platforms: linux/amd64
          push: true
      - name: Sign the container image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign --force ghcr.io/${{ github.repository }}@${{ steps.push-step.outputs.digest }}

      - name: Verify the container image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign verify ghcr.io/${{ github.repository }}@${{ steps.push-step.outputs.digest }}

